### ISSUE TITLE
Announce 3.8.0 beta

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider.github.io#79]

**Comment by bagong** [comment]
I'll have a Windows beta1 build ready sunday night (tomorrow). I spoke with Chris because I'll be away for a while after the 9th of Nov, which means it would be hard to get out a Windows build. Chris agreed to plan to get out the 3.8 release before that. Realistically, I guess, 2 weeks is enough to have people try out/test the beta. Agreed? If yes, it might be good to announce the release one or two weeks in advance.
